# We use a custom profile to keep colcon
# separate from "normal" rust building.
[profile.colcon]
inherits = "release"

[workspace]
members = [
    "thirdparty/arci",
    "thirdparty/arci_ros2",
    "rust_axum_ros2_training",
]