# idl package filtering to reduce build time
[env]
IDL_PACKAGE_FILTER = { value = "std_msgs;sensor_msgs;trajectory_msgs;geometry_msgs;control_msgs;r2r_minimal_node_msgs" }

# for mold
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]